---
execution_environment:
  inspect:
    engine: auto # [auto,podman,docker]
    format: yaml # [yaml,json]
  init:
    version: 3
    additional_build_files:
      - src: files/ansible.cfg
        dest: configs
    ee_base_image: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
    additional_build_steps:
      prepend_galaxy:
        - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
      append_final:
        - RUN echo 'Build completed (ansible-butler)'
    # latest as of 03-13-24
    dependencies:
      system:
        - git
      python:
        - jmespath
      collections:
        - name: ansible.utils
          version: ">=3.1.0"

directory:
  init:
    lint: 
      enabled: true
    code_bot:
      enabled: true
      interval: weekly
    vscode:
      enabled: true
      settings:
        "files.trimTrailingWhitespace": true
        "editor.renderFinalNewline": "on"
        "files.trimFinalNewlines": true
        "ansible.ansible.useFullyQualifiedCollectionNames": true
        "ansible.ansibleNavigator.path": "ansible-navigator"
        "ansible.validation.lint.enabled": true
        "ansible.validation.enabled": true
        "ansible.executionEnvironment.image": "ghcr.io/ansible/creator-ee:latest"
        "ansible.executionEnvironment.enabled": true
        "ansible.executionEnvironment.containerEngine": "auto"
        # "ansible.executionEnvironment.pull.arguments": "--tls-verify=false"
        "ansible.executionEnvironment.pull.policy": "missing"
        "ansible.lightspeed.enabled": true
        "ansible.lightspeed.URL": "https://c.ai.ansible.redhat.com"
        "ansible.lightspeed.suggestions.enabled": true
    folders:
      - name: inventories
        folders:
          - name: example-inventory
            files:
              - hosts
            folders:
              - name: group_vars
              - name: host_vars
      - name: library
      - name: module_utils
      - name: filter_plugins
      - name: roles
    files:
      - playbook.yml.j2
      - ansible.cfg

role:
  dependencies:
    output_fmt: html # [html,json]
    # output_dest: graph.[html|json]
    include_tests: false
    # master_node: role-common-setup # can set in config or pass as <master> argument
    initial_direction: downstream
    title: ansible-butler roles dependency graph
    title_text_color: white
    title_background_color: black
    tree_options:
      animationDuration: 750
      maxDepth: 25
      enableTooltip: true
      enableTooltipKey: true
      # modifyEntityName: null
      # textClick: null
      # maxDepthMessage: null
      # missingEntityMessage: null
      # cyclicDependencyMessage: null
      containerWidthMultiplier: 4
      # containerWidthInPx: null,
      marginTop: 60
      marginRight: 120
      marginBottom: 200
      marginLeft: 120 
      parentNodeTextOrientation: left
      childNodeTextOrientation: right
      textOffset: 13
      textStyleFont: 12px sans-serif
      textStyleColor: black
      circleStrokeColor: '#2b8f91'
      circleStrokeWidth: 3
      circleSize: 10
      linkStrokeColor: '#dddddd'
      linkStrokeWidth: 2
      closedNodeCircleColor: '#9bd3d4'
      openNodeCircleColor: white
      cyclicNodeColor: '#FF4242'
      missingNodeColor: '#CC0100'
      maxDepthNodeColor: '#FF5850'
      horizontalSpaceBetweenNodes: 180
      verticalSpaceBetweenNodes: 30
      wrapNodeName: true
      # splitStr: null
      tooltipItemStyleObj:
        font-family: 'sans-serif'
        font-size: '12px'
      tooltipColonStr: ': '
      tooltipKeyStyleObj: 
        font-weight: bold
      tooltipColonStyleObj:
        font-weight: bold
      tooltipValueStyleObj: {}
      tooltipStyleObj:
        background-color: 'white'
        border: 'solid'
        border-width: '1px'
        border-radius: '5px'
        padding: '10px'

playbook: {}
