JOB_TEMPLATE_URL="/api/v2/job_templates/"
JT_STRIP_KEYS=[
  'id',
  'type',
  'url',
  'related',
  'summary_fields',
  'created',
  'modified',
  'last_job_run',
  'last_job_failed',
  'next_job_run',
  'status'
]
RELATED_STRIP_KEYS=[
  'id',
  'type',
  'url',
  'related',
  'summary_fields',
  'created',
  'modified',
  'unified_job_template',
  'next_run'
]